// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: generator.proto

package go_micro_service_id_generator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GenerateIDService service

func NewGenerateIDServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GenerateIDService service

type GenerateIDService interface {
	// 获取全局唯一自增 id
	GenerateID(ctx context.Context, in *IDReq, opts ...client.CallOption) (*IDResp, error)
}

type generateIDService struct {
	c    client.Client
	name string
}

func NewGenerateIDService(name string, c client.Client) GenerateIDService {
	return &generateIDService{
		c:    c,
		name: name,
	}
}

func (c *generateIDService) GenerateID(ctx context.Context, in *IDReq, opts ...client.CallOption) (*IDResp, error) {
	req := c.c.NewRequest(c.name, "GenerateIDService.GenerateID", in)
	out := new(IDResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GenerateIDService service

type GenerateIDServiceHandler interface {
	// 获取全局唯一自增 id
	GenerateID(context.Context, *IDReq, *IDResp) error
}

func RegisterGenerateIDServiceHandler(s server.Server, hdlr GenerateIDServiceHandler, opts ...server.HandlerOption) error {
	type generateIDService interface {
		GenerateID(ctx context.Context, in *IDReq, out *IDResp) error
	}
	type GenerateIDService struct {
		generateIDService
	}
	h := &generateIDServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&GenerateIDService{h}, opts...))
}

type generateIDServiceHandler struct {
	GenerateIDServiceHandler
}

func (h *generateIDServiceHandler) GenerateID(ctx context.Context, in *IDReq, out *IDResp) error {
	return h.GenerateIDServiceHandler.GenerateID(ctx, in, out)
}
